
    name: Artifact Management

    on:
      release:
        types: [created]
      workflow_dispatch:

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Build Artifacts
          run: |
            mkdir -p dist
            python setup.py sdist bdist_wheel

        - name: Upload Artifact
          uses: actions/upload-artifact@v2
          with:
            name: my-package
            path: dist/*
    