
name: Automated Software Development Process with Detailed Logging

on:
  workflow_dispatch:  # Allows manual triggering for the initial user input

jobs:
  initial_prompt:
    runs-on: ubuntu-latest
    steps:
    - name: Prompt user for initial description
      run: |
        echo "Please provide a brief description of the project you would like to create:"
        read user_description
        echo "User description received: $user_description"
        echo "::set-output name=user_description::$user_description"
      id: prompt_user

  enrich_and_test:
    needs: initial_prompt
    runs-on: ubuntu-latest
    strategy:
      matrix:
        iteration: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]  # 10 enrichments per stage
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Auto-enrich project on iteration ${{ matrix.iteration }}
      run: |
        echo "Enriching the project at iteration ${{ matrix.iteration }}..."
        python auto_enrich.py --iteration ${{ matrix.iteration }} --description "${{ needs.prompt_user.outputs.user_description }}"
        echo "Auto-enrichment completed for iteration ${{ matrix.iteration }}."
        
    - name: Test and Bug Check at Stage ${{ matrix.iteration }}
      run: |
        echo "Running tests and bug check at iteration ${{ matrix.iteration }}..."
        pytest
        echo "Tests completed for iteration ${{ matrix.iteration }}."

    - name: Auto-correct errors (if any)
      run: |
        echo "Checking for errors to auto-correct..."
        python auto_correct.py
        echo "Auto-correction completed for iteration ${{ matrix.iteration }}."

  finalize_project:
    needs: enrich_and_test
    runs-on: ubuntu-latest
    steps:
    - name: Finalize project and present to user
      run: |
        echo "Finalizing the project after all iterations..."
        python finalize_project.py
        echo "Project finalized."

    - name: Notify user of completed project
      run: echo "Your enhanced and fully developed project is ready!"
