
    name: CI/CD with Staging and Production

    on:
      push:
        branches:
          - staging
          - production
      pull_request:
        branches:
          - staging
          - production
      workflow_dispatch:

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Build and Test
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pytest

      deploy_staging:
        if: github.ref == 'refs/heads/staging'
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Deploy to Staging
          run: echo "Deploying to Staging"

      deploy_production:
        if: github.ref == 'refs/heads/production'
        runs-on: ubuntu-latest
        needs: build
        steps:
        - name: Deploy to Production
          run: echo "Deploying to Production"
    