
    name: Deployment Check

    on:
      workflow_dispatch:

    jobs:
      check:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Run Deployment Check
          run: echo "Running deployment check for errors."
    