
    name: Rolling Update Deployment

    on:
      push:
        branches:
          - main
      workflow_dispatch:  # Added workflow_dispatch to enable manual triggering

    jobs:
      rolling_update:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Run Rolling Update
          run: |
            echo "Rolling update in progress..."
    